language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coveralls
script:
    - pytest
after_success:
    - if [[ $ENV == python=3.6* ]]; then
          coveralls;
      fi
